### PR TITLE
poplar: Raise kernel txt offset by 32mb

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Make room for op-tee

**Comment by fboudra** [comment]
@vchong fwiw, "make room for OP-TEE" should be in the commit message ;)

**Comment by vchong** [comment]
@fboudra Commit message updated. Thanks! :)

**Comment by shawnguo2** [comment]
@vchong Can we get optee run at high address, so that the low address definitions can be independent to whether optee is enabled or not?

**Comment by vchong** [comment]
> Can we get optee run at high address, so that the low address definitions can be independent to whether optee is enabled or not?

@shawnguo2 High address was actually what I tried first, but something is not honoring the high address memory reservation in both u-boot and dt, and keep using/overwriting the area, so it's not working. In any case, we can't really say that low address definition is dependent on op-tee or not. Generally speaking, `KERNEL_TEXT_OFFSET` by itself is really just a memory reservation for arm-tf at low address. If use high address for op-tee, then we'll need to create another reservation at high address, i.e. still have to change some code in u-boot anyway. Then, we'll end up with two reserved areas, one at low address and another at high address. This is maybe ok for 1GB board, but for 2 GB board, we'll end up with fragmented usable memory areas which can possibly affect performance. So low address not only works for op-tee, it's also the better option since we just keep one reservation only (by making it larger) for better performance and also group the secure bootloaders together, making it easier to protect later.

**Comment by shawnguo2** [comment]
> So low address not only works for op-tee, it's also the better option since we just keep one reservation only (by making it larger) for better performance and also group the secure bootloaders together, making it easier to protect later.

So is it the approach used on Hikey as well?  And is this U-Boot change independent to DT change below?  Or is there a dependency between them?
`/memreserve/ 0x00000000 0x02080000;`
`/* reserved for bootloader */`

**Comment by vchong** [comment]
> So is it the approach used on Hikey as well? And is this U-Boot change independent to DT change below? Or is there a dependency between them?
/memreserve/ 0x00000000 0x02080000;
/* reserved for bootloader */

No. Hikey has sram so l-loader and arm-tf are loaded there. U-boot change is independent to DT change. DT change is just backup or extra precaution.

**Comment by vchong** [comment]
Replaced by #3

**Pull request closed without merging**
